server {
    listen 80;

    # Serve the React App
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Required for React Router
    }

    # Proxy API requests to the Backend Container
    location /api/ {
        proxy_pass http://backend:5500/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Serve Uploaded Images (Receipts)
    location /uploads/ {
        proxy_pass http://backend:5500/uploads/;
    }
}
